import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { db } from '../../lib/supabase';
import { Article } from '../../data/sampleArticles';
import { LoadingState } from '../../components/States';
import { Save, ArrowLeft, Image as ImageIcon, Sparkles, HelpCircle, Eye } from 'lucide-react';

const CATEGORIES = [
  "Children & Adolescents",
  "Emotional Wellbeing",
  "Stress & Anxiety",
  "Relationship Concerns",
  "Self-Esteem",
  "Women’s Emotional Wellbeing",
  "Personal Growth"
];

export default function AdminPostEditor() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const isEditMode = !!id;

  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  // Form states
  const [title, setTitle] = useState('');
  const [slug, setSlug] = useState('');
  const [excerpt, setExcerpt] = useState('');
  const [content, setContent] = useState('');
  const [category, setCategory] = useState(CATEGORIES[1]); // Default to "Emotional Wellbeing"
  const [tags, setTags] = useState('');
  const [featuredImage, setFeaturedImage] = useState('');
  const [readingTime, setReadingTime] = useState('4 min read');
  const [status, setStatus] = useState<'draft' | 'published'>('draft');
  const [postRecord, setPostRecord] = useState<Article | null>(null);

  // File upload state
  const [uploadingFile, setUploadingFile] = useState(false);

  useEffect(() => {
    document.title = isEditMode ? "Edit Article | Peaceful Mind Admin" : "Create Article | Peaceful Mind Admin";
    
    if (isEditMode) {
      const loadPost = async () => {
        setLoading(true);
        try {
          const post = await db.getPostById(id);
          if (post) {
            setPostRecord(post);
            setTitle(post.title);
            setSlug(post.slug);
            setExcerpt(post.excerpt);
            setContent(post.content);
            setCategory(post.category);
            setTags(post.tags.join(', '));
            setFeaturedImage(post.featured_image);
            setReadingTime(post.reading_time);
            setStatus(post.status);
          } else {
            setError('Article not found.');
          }
        } catch (e) {
          console.error(e);
          setError('Error loading article data.');
        } finally {
          setLoading(false);
        }
      };
      loadPost();
    }
  }, [id, isEditMode]);

  // Slug Autogeneration based on title
  const handleTitleChange = (val: string) => {
    setTitle(val);
    if (!isEditMode) {
      const autogenerated = val
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '') // remove special chars
        .replace(/\s+/g, '-')         // replace spaces with dashes
        .replace(/-+/g, '-');        // replace repeated dashes
      setSlug(autogenerated);
    }
  };

  // Content change auto calculation for reading time
  const handleContentChange = (val: string) => {
    setContent(val);
    // Rough calculation: ~200 words per minute
    const cleanText = val.replace(/<[^>]*>/g, ''); // strip HTML tags
    const wordCount = cleanText.trim().split(/\s+/).filter(Boolean).length;
    const mins = Math.max(1, Math.ceil(wordCount / 200));
    setReadingTime(`${mins} min read`);
  };

  // Local File Upload trigger
  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      alert("Please upload an image file (PNG, JPG, WEBP).");
      return;
    }

    if (file.size > 5 * 1024 * 1024) {
      alert("Image size must be smaller than 5MB.");
      return;
    }

    setUploadingFile(true);
    try {
      const url = await db.uploadMedia(file);
      setFeaturedImage(url);
      alert("Image uploaded successfully and set as Featured Image!");
    } catch (err) {
      console.error(err);
      alert("Error uploading file. Falling back to input URL.");
    } finally {
      setUploadingFile(false);
    }
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');

    if (!title.trim() || !slug.trim() || !excerpt.trim() || !content.trim()) {
      setError('Title, Slug, Excerpt, and Article Content are required fields.');
      return;
    }

    // Verify slug uniqueness against other posts
    setSaving(true);
    try {
      const allPosts = await db.getPosts({ includeDrafts: true });
      const duplicate = allPosts.find(p => p.slug === slug.trim() && p.id !== id);
      if (duplicate) {
        setError(`A post already exists with the slug "${slug}". Please provide a unique slug.`);
        setSaving(false);
        return;
      }

      // Format tags
      const formattedTags = tags
        .split(',')
        .map(t => t.trim())
        .filter(Boolean);

      const savedPost = await db.savePost({
        id: id, // undefined if creating
        title: title.trim(),
        slug: slug.trim(),
        excerpt: excerpt.trim(),
        content: content, // rich HTML/markdown string
        category: category,
        tags: formattedTags,
        featured_image: featuredImage.trim(),
        reading_time: readingTime,
        status: status,
        likes_count: postRecord?.likes_count || 0,
        created_at: postRecord?.created_at
      });

      setSuccess(isEditMode ? 'Changes saved successfully!' : 'Article published successfully!');
      
      // Navigate back after a small success display
      setTimeout(() => {
        navigate('/admin/posts');
      }, 1500);

    } catch (err: any) {
      console.error(err);
      setError(err.message || 'An error occurred while saving the post.');
    } finally {
      setSaving(false);
    }
  };

  // Helper editor formatting buttons
  const insertStyle = (tagOpen: string, tagClose: string) => {
    const textarea = document.getElementById('post-body') as HTMLTextAreaElement;
    if (!textarea) return;

    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const text = textarea.value;

    const selected = text.substring(start, end);
    const replacement = tagOpen + (selected || "text") + tagClose;

    const newValue = text.substring(0, start) + replacement + text.substring(end);
    setContent(newValue);
    
    // Set focus back
    setTimeout(() => {
      textarea.focus();
      textarea.setSelectionRange(start + tagOpen.length, start + tagOpen.length + (selected || "text").length);
    }, 50);
  };

  if (loading) {
    return <LoadingState message="Loading article editor workspace..." />;
  }

  return (
    <div className="space-y-8 animate-fadeIn">
      
      {/* Title */}
      <div className="flex items-center space-x-3">
        <Link
          to="/admin/posts"
          className="p-2 border border-sage/15 rounded-xl hover:bg-cream hover:text-sage text-slate-dark transition-colors shrink-0"
        >
          <ArrowLeft size={16} />
        </Link>
        <div>
          <h1 className="font-serif text-2xl font-bold text-slate-dark">
            {isEditMode ? 'Edit Article Insights' : 'Write Therapeutic Article'}
          </h1>
          <p className="text-xs text-slate-dark/60 mt-0.5">
            {isEditMode ? `Modifying: ${postRecord?.title}` : 'Draft reflections, mindfulness techniques, and healthy relationship tools.'}
          </p>
        </div>
      </div>

      {error && (
        <p className="text-pink text-xs font-semibold bg-pink/5 border border-pink/15 p-4 rounded-xl">
          {error}
        </p>
      )}

      {success && (
        <p className="text-sage text-xs font-semibold bg-sage/5 border border-sage/15 p-4 rounded-xl">
          {success}
        </p>
      )}

      <form onSubmit={handleSave} className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Left Side Content Column */}
        <div className="lg:col-span-8 bg-white border border-sage/10 p-6 sm:p-8 rounded-3xl shadow-sm space-y-6">
          
          {/* Article Title */}
          <div className="space-y-1.5">
            <label htmlFor="post-title" className="text-xs font-bold tracking-wide text-slate-dark/70 uppercase">
              Article Title *
            </label>
            <input
              type="text"
              id="post-title"
              required
              disabled={saving}
              value={title}
              onChange={(e) => handleTitleChange(e.target.value)}
              placeholder="e.g. Managing Everyday Stress"
              className="w-full px-4 py-3 rounded-xl bg-cream/20 border border-sage/15 text-slate-dark text-sm focus:outline-none focus:border-sage"
            />
          </div>

          {/* Slug input */}
          <div className="space-y-1.5">
            <label htmlFor="post-slug" className="text-xs font-bold tracking-wide text-slate-dark/70 uppercase">
              Unique URL Slug *
            </label>
            <div className="flex rounded-xl overflow-hidden border border-sage/15">
              <span className="bg-cream/50 px-3.5 py-3 text-slate-dark/50 text-xs sm:text-sm border-r border-sage/15 flex items-center shrink-0">
                /blog/
              </span>
              <input
                type="text"
                id="post-slug"
                required
                disabled={saving}
                value={slug}
                onChange={(e) => setSlug(e.target.value.toLowerCase().replace(/\s+/g, '-'))}
                placeholder="managing-everyday-stress"
                className="w-full px-4 py-3 bg-cream/20 text-slate-dark text-sm focus:outline-none focus:border-sage"
              />
            </div>
          </div>

          {/* Excerpt */}
          <div className="space-y-1.5">
            <label htmlFor="post-excerpt" className="text-xs font-bold tracking-wide text-slate-dark/70 uppercase">
              Article Excerpt / Sub-headline *
            </label>
            <textarea
              id="post-excerpt"
              required
              disabled={saving}
              rows={3}
              value={excerpt}
              onChange={(e) => setExcerpt(e.target.value)}
              placeholder="Provide a clean, engaging 2-sentence summary of the article to be shown in grids and catalog lists..."
              className="w-full px-4 py-3 rounded-xl bg-cream/20 border border-sage/15 text-slate-dark text-sm focus:outline-none focus:border-sage"
            />
          </div>

          {/* Content rich text area (with helpful text triggers) */}
          <div className="space-y-2">
            <div className="flex justify-between items-center">
              <label htmlFor="post-body" className="text-xs font-bold tracking-wide text-slate-dark/70 uppercase">
                Article Body Content (HTML / Text) *
              </label>
              
              {/* Text formatting tags insert */}
              <div className="hidden sm:flex items-center space-x-1">
                <button
                  type="button"
                  onClick={() => insertStyle('<h2>', '</h2>')}
                  className="px-2 py-1 bg-cream/50 border border-sage/15 text-[10px] font-bold rounded hover:bg-sage/10 text-slate-dark"
                  title="Heading 2"
                >
                  H2
                </button>
                <button
                  type="button"
                  onClick={() => insertStyle('<h3>', '</h3>')}
                  className="px-2 py-1 bg-cream/50 border border-sage/15 text-[10px] font-bold rounded hover:bg-sage/10 text-slate-dark"
                  title="Heading 3"
                >
                  H3
                </button>
                <button
                  type="button"
                  onClick={() => insertStyle('<strong>', '</strong>')}
                  className="px-2 py-1 bg-cream/50 border border-sage/15 text-[10px] font-bold rounded hover:bg-sage/10 text-slate-dark font-black"
                  title="Bold text"
                >
                  B
                </button>
                <button
                  type="button"
                  onClick={() => insertStyle('<em>', '</em>')}
                  className="px-2 py-1 bg-cream/50 border border-sage/15 text-[10px] font-bold rounded hover:bg-sage/10 text-slate-dark italic"
                  title="Italic text"
                >
                  I
                </button>
                <button
                  type="button"
                  onClick={() => insertStyle('<blockquote>', '</blockquote>')}
                  className="px-2 py-1 bg-cream/50 border border-sage/15 text-[10px] font-bold rounded hover:bg-sage/10 text-slate-dark"
                  title="Blockquote"
                >
                  Quote
                </button>
                <button
                  type="button"
                  onClick={() => insertStyle('<ul>\n  <li>', '</li>\n</ul>')}
                  className="px-2 py-1 bg-cream/50 border border-sage/15 text-[10px] font-bold rounded hover:bg-sage/10 text-slate-dark"
                  title="Unordered List"
                >
                  List
                </button>
              </div>
            </div>

            <textarea
              id="post-body"
              required
              disabled={saving}
              rows={15}
              value={content}
              onChange={(e) => handleContentChange(e.target.value)}
              placeholder="Write your beautiful article body here. Support standard HTML formatting tags like <h2>, <p>, <strong>, <em>, <ul>, and <li> to create elegant reading paragraphs..."
              className="w-full px-4 py-3 rounded-xl bg-cream/20 border border-sage/15 text-slate-dark text-sm focus:outline-none focus:border-sage font-mono leading-relaxed"
            />
          </div>

        </div>

        {/* Right Side Settings Column */}
        <div className="lg:col-span-4 space-y-6">
          
          {/* Action Panel */}
          <div className="bg-white border border-sage/10 p-6 rounded-3xl shadow-sm space-y-4">
            <h3 className="font-serif font-bold text-slate-dark text-base">Publish Settings</h3>
            
            {/* Status dropdown */}
            <div className="space-y-1.5">
              <label htmlFor="post-status" className="text-xs font-bold tracking-wide text-slate-dark/70 uppercase">
                Publishing Status
              </label>
              <select
                id="post-status"
                value={status}
                disabled={saving}
                onChange={(e) => setStatus(e.target.value as any)}
                className="w-full px-3.5 py-2.5 rounded-xl bg-cream/20 border border-sage/15 text-slate-dark text-sm focus:outline-none focus:border-sage"
              >
                <option value="draft">Draft (Private / Hidden)</option>
                <option value="published">Published (Public on Website)</option>
              </select>
            </div>

            {/* Reading time indicator display */}
            <div className="space-y-1.5">
              <label htmlFor="reading-time" className="text-xs font-bold tracking-wide text-slate-dark/70 uppercase">
                Estimated Reading Time
              </label>
              <input
                type="text"
                id="reading-time"
                value={readingTime}
                onChange={(e) => setReadingTime(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-xl bg-cream/20 border border-sage/15 text-slate-dark text-sm focus:outline-none focus:border-sage"
              />
            </div>

            {/* Save trigger */}
            <button
              type="submit"
              disabled={saving}
              className="w-full inline-flex items-center justify-center px-5 py-3 rounded-xl bg-sage hover:bg-slate-dark text-cream text-sm font-semibold transition-all duration-300 shadow-md active:scale-98 disabled:opacity-50 space-x-2"
            >
              <Save size={15} />
              <span>{saving ? 'Saving changes...' : (isEditMode ? 'Save Article' : 'Publish Article')}</span>
            </button>
          </div>

          {/* Categories & Tags Panel */}
          <div className="bg-white border border-sage/10 p-6 rounded-3xl shadow-sm space-y-4">
            <h3 className="font-serif font-bold text-slate-dark text-base font-medium">Categorization</h3>

            {/* Category selection */}
            <div className="space-y-1.5">
              <label htmlFor="post-category" className="text-xs font-bold tracking-wide text-slate-dark/70 uppercase">
                Article Category *
              </label>
              <select
                id="post-category"
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-xl bg-cream/20 border border-sage/15 text-slate-dark text-sm focus:outline-none focus:border-sage"
              >
                {CATEGORIES.map((cat) => (
                  <option key={cat} value={cat}>{cat}</option>
                ))}
              </select>
            </div>

            {/* Tags (comma separated) */}
            <div className="space-y-1.5">
              <label htmlFor="post-tags" className="text-xs font-bold tracking-wide text-slate-dark/70 uppercase">
                Keywords / Tags
              </label>
              <input
                type="text"
                id="post-tags"
                value={tags}
                onChange={(e) => setTags(e.target.value)}
                placeholder="e.g. Stress, Mindfulness, Self-Care"
                className="w-full px-3.5 py-2.5 rounded-xl bg-cream/20 border border-sage/15 text-slate-dark text-sm focus:outline-none focus:border-sage"
              />
              <p className="text-[10px] text-slate-dark/40 italic">Separate with commas</p>
            </div>

          </div>

          {/* Media & Featured Image Panel */}
          <div className="bg-white border border-sage/10 p-6 rounded-3xl shadow-sm space-y-4">
            <h3 className="font-serif font-bold text-slate-dark text-base font-medium">Featured Graphic</h3>

            {/* Thumbnail preview */}
            {featuredImage && (
              <div className="aspect-[16/9] bg-cream rounded-xl border border-sage/10 overflow-hidden relative group">
                <img
                  src={featuredImage}
                  alt="Featured illustration preview"
                  className="w-full h-full object-cover"
                />
              </div>
            )}

            {/* Pasted Image URL */}
            <div className="space-y-1.5">
              <label htmlFor="featured-image-url" className="text-xs font-bold tracking-wide text-slate-dark/70 uppercase">
                Image Public URL
              </label>
              <input
                type="url"
                id="featured-image-url"
                value={featuredImage}
                onChange={(e) => setFeaturedImage(e.target.value)}
                placeholder="Paste external Unsplash image URL..."
                className="w-full px-3.5 py-2.5 rounded-xl bg-cream/20 border border-sage/15 text-slate-dark text-sm focus:outline-none focus:border-sage"
              />
            </div>

            {/* Native file upload selector */}
            <div className="space-y-1.5">
              <span className="text-xs font-bold tracking-wide text-slate-dark/70 uppercase block">
                Or Upload File
              </span>
              <label className="w-full flex items-center justify-center space-x-2 px-3.5 py-2.5 rounded-xl bg-cream/50 border border-dashed border-sage/20 hover:border-sage cursor-pointer text-xs font-semibold text-slate-dark/60 hover:text-sage transition-all">
                <ImageIcon size={14} />
                <span>{uploadingFile ? 'Uploading File...' : 'Choose image file'}</span>
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleFileUpload}
                  disabled={uploadingFile}
                  className="hidden"
                />
              </label>
              <p className="text-[9px] text-slate-dark/40 italic">Accepts JPG, PNG, WEBP (Max 5MB)</p>
            </div>

          </div>

        </div>

      </form>

    </div>
  );
}
